{% set name = "imodmodel" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imodmodel-{{ version }}.tar.gz
  sha256: 8d0733c734a4c07f4b668bd7df4c32c32f9ecff29e54c7af8b98d7a0c5900508

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.8
  run:
    - numpy
    - pandas
    - pydantic
    - python >=3.8

test:
  imports:
    - imodmodel
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/imodmodel
  summary: IMOD model files as pandas DataFrames in Python.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/teamtomo/imodmodel

extra:
  recipe-maintainers:
    - goanpeca
